server:
  version: 1.0
  host: localhost
  port: :4000

mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: education
  charset: utf8mb4

neo4j:
  host: localhost
  port: 7687
  username: neo4j
  password: password

python:
  baseurl: http://localhost:8000

migrate:
  auto: true
  userdatapath: ./configs/users.csv
  experimentdetailsdatapath: ./configs/experiment_details.json
